version: "3"
services:
    app:
        build: ./php-fpm
        depends_on:
            - db
        restart: always
        volumes:
            - ./app/:/var/www
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    nginx:
        image: nginx:1.13
        depends_on:
            - app
        ports:
            - 80:80
        restart: always
        volumes:
            - ./app/:/var/www
            - ./log/nginx/:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
